# Clock
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_left/steer_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/front_left_steer_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/front_left/wheel_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/front_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/front_right/steer_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/front_right_steer_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/front_right/wheel_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/front_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rear_left/steer_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/rear_left_steer_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rear_left/wheel_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/rear_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rear_right/steer_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/rear_right_steer_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rear_right/wheel_joint/cmd_vel"
  gz_topic_name: "/model/cestra_swerve/joint/rear_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

########## Unified Joint States ##########
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/cestra_swerve/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
