<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link ="imu_link"/>
    <origin xyz="${base_length / 2} 0 ${base_height + imu_height}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}" />
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>100</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <imu>
        <angular_velocity>
          <x><noise type="gaussian"><mean>0.0</mean><stddev>0.0002</stddev></noise></x>
          <y><noise type="gaussian"><mean>0.0</mean><stddev>0.0002</stddev></noise></y>
          <z><noise type="gaussian"><mean>0.0</mean><stddev>0.0002</stddev></noise></z>
        </angular_velocity>
        <linear_acceleration>
          <x><noise type="gaussian"><mean>0.0</mean><stddev>0.017</stddev></noise></x>
          <y><noise type="gaussian"><mean>0.0</mean><stddev>0.017</stddev></noise></y>
          <z><noise type="gaussian"><mean>0.0</mean><stddev>0.017</stddev></noise></z>
        </linear_acceleration>
      </imu>
      <topic>imu</topic>
      <gz_frame_id>imu_link</gz_frame_id>
    </sensor>
  </gazebo>
</robot>

